global using Bunit;
global using FluentAssertions;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Xunit;

global using Alert = MyStackBlazor.Components.Data.StackAlert;
global using AlertDescription = MyStackBlazor.Components.Data.StackAlertDescription;
global using AlertTitle = MyStackBlazor.Components.Data.StackAlertTitle;
global using Avatar = MyStackBlazor.Components.Common.StackAvatar;
global using Badge = MyStackBlazor.Components.Common.StackBadge;
global using BarChart = MyStackBlazor.Components.Charts.StackBarChart;
global using Breadcrumb = MyStackBlazor.Components.Navigation.StackBreadcrumb;
global using BreadcrumbItem = MyStackBlazor.Components.Navigation.StackBreadcrumbItem;
global using Button = MyStackBlazor.Components.Common.StackButton;
global using Card = MyStackBlazor.Components.Layout.StackCard;
global using Checkbox = MyStackBlazor.Components.Form.StackCheckbox;
global using Collapsible = MyStackBlazor.Components.Layout.StackCollapsible;
global using Input = MyStackBlazor.Components.Form.StackInput;
global using LineChart = MyStackBlazor.Components.Charts.StackLineChart;
global using MarkdownEditor = MyStackBlazor.Components.Form.StackMarkdownEditor;
global using MsCalendar = MyStackBlazor.Components.Calendar.StackMsCalendar;
global using NumericInput = MyStackBlazor.Components.Form.StackNumericInput;
global using PieChart = MyStackBlazor.Components.Charts.StackPieChart;
global using Progress = MyStackBlazor.Components.Data.StackProgress;
global using RadioGroup = MyStackBlazor.Components.Form.StackRadioGroup;
global using Rating = MyStackBlazor.Components.Form.StackRating;
global using Select = MyStackBlazor.Components.Form.StackSelect;
global using Skeleton = MyStackBlazor.Components.Common.StackSkeleton;
global using Slider = MyStackBlazor.Components.Form.StackSlider;
global using Spinner = MyStackBlazor.Components.Common.StackSpinner;
global using Switch = MyStackBlazor.Components.Form.StackSwitch;
global using Textarea = MyStackBlazor.Components.Form.StackTextarea;
global using Typography = MyStackBlazor.Components.Common.StackTypography;
